import Link from "next/link";

const STEPS = [
  {
    number: "01",
    title: "Understand",
    description:
      "AI turns a natural-language customer message into structured invoice details.",
  },
  {
    number: "02",
    title: "Verify",
    description:
      "Requested services are matched against your service catalog and verified prices.",
  },
  {
    number: "03",
    title: "Calculate",
    description:
      "The application calculates quantities, subtotals, tax, and totals deterministically.",
  },
  {
    number: "04",
    title: "Review",
    description:
      "You review the invoice and approve it before the final PDF is exported.",
  },
];

const FEATURES = [
  {
    number: "01",
    title: "Natural-language requests",
    description:
      "Customers can describe what they need in normal language instead of filling out a rigid invoice form.",
  },
  {
    number: "02",
    title: "AI-powered extraction",
    description:
      "Customer details, requested services, quantities, and notes are extracted into structured invoice information.",
  },
  {
    number: "03",
    title: "Verified service pricing",
    description:
      "Prices come from your service catalog. If a service cannot be confidently matched, it is flagged for review.",
  },
  {
    number: "04",
    title: "Automatic calculations",
    description:
      "Line totals, subtotal, tax, and grand total are calculated by the application rather than generated by AI.",
  },
  {
    number: "05",
    title: "Human approval",
    description:
      "You remain in control. The invoice must be reviewed and approved before it can be exported.",
  },
  {
    number: "06",
    title: "Professional PDF",
    description:
      "Approved invoices can be exported as professional, customer-ready PDF documents.",
  },
];

const PRINCIPLES = [
  {
    title: "AI interprets the request",
    description:
      "AI handles the language understanding layer and extracts useful invoice information.",
  },
  {
    title: "Your catalog controls pricing",
    description:
      "The service catalog is the source of truth for service prices.",
  },
  {
    title: "The application calculates money",
    description:
      "Financial calculations are handled deterministically by the application.",
  },
  {
    title: "A human approves before export",
    description:
      "Final approval stays with the person responsible for the invoice.",
  },
];

export default function HomePage() {
  return (
    <div className="min-h-screen scroll-smooth overflow-x-clip bg-ink text-white">
      {/* Navigation */}
      <header className="sticky top-0 z-50 border-b border-white/10 bg-ink/95 shadow-lg shadow-black/10 backdrop-blur-xl">
        <div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-6 px-5 sm:px-6 lg:px-8">
          {/* Brand */}
          <Link href="/" className="flex shrink-0 items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gold text-ink">
              <span className="font-serif text-lg font-bold">IP</span>
            </div>

            <div>
              <p className="font-serif text-xl tracking-tight">
                InvoicePilot AI
              </p>

              <p className="hidden text-[10px] uppercase tracking-[0.2em] text-white/40 sm:block">
                Smart invoicing
              </p>
            </div>
          </Link>

          {/* Right-side desktop navigation */}
          <div className="hidden items-center gap-7 lg:flex">
            <nav className="flex items-center gap-7">
              <a
                href="#features"
                className="text-sm font-medium text-white/60 transition hover:text-white"
              >
                Features
              </a>

              <a
                href="#how-it-works"
                className="text-sm font-medium text-white/60 transition hover:text-white"
              >
                How it works
              </a>

              <a
                href="#why-invoicepilot"
                className="text-sm font-medium text-white/60 transition hover:text-white"
              >
                Why InvoicePilot
              </a>

              <a
                href="#feedback"
                className="text-sm font-medium text-white/60 transition hover:text-white"
              >
                Feedback
              </a>
            </nav>

            <div className="h-6 w-px bg-white/10" />

            <div className="flex items-center gap-2">
              <Link
                href="/login"
                className="rounded-full px-4 py-2.5 text-sm font-medium text-white/70 transition hover:bg-white/10 hover:text-white"
              >
                Sign in
              </Link>

              <Link
                href="/signup"
                className="rounded-full bg-gold px-5 py-2.5 text-sm font-medium text-ink shadow-sm transition hover:-translate-y-0.5 hover:bg-gold/90"
              >
                Get started
              </Link>
            </div>
          </div>

          {/* Compact actions for smaller screens */}
          <div className="flex items-center gap-2 lg:hidden">
            <Link
              href="/login"
              className="rounded-full px-3 py-2 text-sm font-medium text-white/70 transition hover:bg-white/10 hover:text-white"
            >
              Sign in
            </Link>

            <Link
              href="/signup"
              className="rounded-full bg-gold px-4 py-2.5 text-sm font-medium text-ink shadow-sm transition hover:bg-gold/90"
            >
              Get started
            </Link>
          </div>
        </div>

        {/* Mobile section navigation */}
        <div className="border-t border-white/10 lg:hidden">
          <nav className="mx-auto flex max-w-7xl items-center gap-6 overflow-x-auto px-5 py-3 sm:px-6">
            <a
              href="#features"
              className="shrink-0 text-xs font-medium text-white/55 transition hover:text-white"
            >
              Features
            </a>

            <a
              href="#how-it-works"
              className="shrink-0 text-xs font-medium text-white/55 transition hover:text-white"
            >
              How it works
            </a>

            <a
              href="#why-invoicepilot"
              className="shrink-0 text-xs font-medium text-white/55 transition hover:text-white"
            >
              Why InvoicePilot
            </a>

            <a
              href="#feedback"
              className="shrink-0 text-xs font-medium text-white/55 transition hover:text-white"
            >
              Feedback
            </a>
          </nav>
        </div>
      </header>

      <main>
        {/* Hero */}
        <section className="relative">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(196,163,90,0.16),transparent_35%)]" />

          <div className="relative mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-6 sm:py-24 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-8 lg:py-28">
            <div>
              <p className="text-sm font-medium uppercase tracking-[0.25em] text-gold">
                Kodnexus · Smart Invoice Challenge
              </p>

              <h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">
                Turn customer messages into professional invoices.
              </h1>

              <p className="mt-7 max-w-2xl text-lg leading-8 text-white/65 sm:text-xl">
                InvoicePilot AI transforms natural-language customer requests
                into structured, price-verified invoices that are ready for
                human review and approval.
              </p>

              <div className="mt-9 flex flex-wrap gap-4">
                <Link
                  href="/signup"
                  className="rounded-full bg-gold px-7 py-3.5 font-medium text-ink shadow-lg transition hover:-translate-y-0.5 hover:bg-gold/90"
                >
                  Create your first invoice
                </Link>

                <a
                  href="#how-it-works"
                  className="rounded-full border border-white/15 px-7 py-3.5 font-medium text-white transition hover:bg-white/10"
                >
                  See how it works
                </a>
              </div>

              <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-white/45">
                <span>✓ AI-assisted extraction</span>
                <span>✓ Catalog-based pricing</span>
                <span>✓ Human approval</span>
              </div>
            </div>

            {/* Example */}
            <div className="relative">
              <div className="absolute -inset-6 rounded-[2rem] bg-gold/10 blur-3xl" />

              <div className="relative rounded-[2rem] border border-white/10 bg-white/[0.06] p-5 shadow-2xl backdrop-blur-sm sm:p-7">
                <div className="flex items-center justify-between border-b border-white/10 pb-5">
                  <div>
                    <p className="text-xs uppercase tracking-[0.2em] text-gold">
                      Customer request
                    </p>

                    <p className="mt-2 text-sm text-white/50">
                      Natural language input
                    </p>
                  </div>

                  <span className="rounded-full bg-white/10 px-3 py-1.5 text-xs text-white/60">
                    AI extraction
                  </span>
                </div>

                <div className="mt-5 rounded-2xl bg-white/5 p-5">
                  <p className="text-sm leading-7 text-white/80">
                    “Hi, I need an e-commerce website and SEO optimization.
                    Please make one of each for Rahul. My email is
                    rahul@example.com.”
                  </p>
                </div>

                <div className="my-6 flex justify-center text-gold">
                  <span className="text-xl">↓</span>
                </div>

                <div className="rounded-2xl bg-[#f7f4ee] p-5 text-ink">
                  <div className="flex items-start justify-between gap-4 border-b border-ink/10 pb-4">
                    <div>
                      <p className="font-serif text-xl">Invoice</p>

                      <p className="mt-1 text-xs text-ink/45">
                        Structured & price verified
                      </p>
                    </div>

                    <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-medium text-amber-800">
                      Needs Review
                    </span>
                  </div>

                  <div className="mt-5 space-y-3 text-sm">
                    <div className="flex justify-between gap-4">
                      <span className="text-ink/60">
                        E-commerce Website × 1
                      </span>

                      <span className="font-medium">₹65,000</span>
                    </div>

                    <div className="flex justify-between gap-4">
                      <span className="text-ink/60">
                        SEO Optimization × 1
                      </span>

                      <span className="font-medium">₹12,000</span>
                    </div>
                  </div>

                  <div className="mt-5 border-t border-ink/10 pt-4">
                    <div className="flex justify-between text-sm">
                      <span className="text-ink/55">Subtotal</span>

                      <span className="font-medium">₹77,000</span>
                    </div>

                    <div className="mt-2 flex justify-between text-sm">
                      <span className="text-ink/55">Tax</span>

                      <span className="font-medium">₹13,860</span>
                    </div>

                    <div className="mt-4 flex justify-between border-t border-ink/10 pt-4">
                      <span className="font-medium">Grand Total</span>

                      <span className="font-serif text-xl font-bold">
                        ₹90,860
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Features */}
        <section
          id="features"
          className="scroll-mt-28 border-y border-white/10 bg-white/[0.025]"
        >
          <div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 lg:px-8 lg:py-24">
            <div className="max-w-2xl">
              <p className="text-sm font-medium uppercase tracking-[0.22em] text-gold">
                Features
              </p>

              <h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">
                Everything between the message and the invoice.
              </h2>

              <p className="mt-5 text-lg leading-8 text-white/55">
                A focused workflow designed to make invoice creation faster
                without giving up control over pricing or approval.
              </p>
            </div>

            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {FEATURES.map((feature) => (
                <div
                  key={feature.number}
                  className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 transition hover:-translate-y-1 hover:bg-white/[0.07]"
                >
                  <p className="text-sm font-medium text-gold">
                    {feature.number}
                  </p>

                  <h3 className="mt-4 font-serif text-2xl">
                    {feature.title}
                  </h3>

                  <p className="mt-3 text-sm leading-6 text-white/50">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How it works */}
        <section
          id="how-it-works"
          className="scroll-mt-28 border-b border-white/10"
        >
          <div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 lg:px-8 lg:py-24">
            <div className="max-w-2xl">
              <p className="text-sm font-medium uppercase tracking-[0.22em] text-gold">
                How it works
              </p>

              <h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">
                From customer message to approved invoice.
              </h2>

              <p className="mt-5 text-lg leading-8 text-white/55">
                Each step has a clear responsibility, keeping AI
                interpretation separate from pricing and financial
                calculations.
              </p>
            </div>

            <div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              {STEPS.map((step) => (
                <div
                  key={step.number}
                  className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"
                >
                  <p className="text-sm font-medium text-gold">
                    {step.number}
                  </p>

                  <h3 className="mt-4 font-serif text-2xl">
                    {step.title}
                  </h3>

                  <p className="mt-3 text-sm leading-6 text-white/50">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Why InvoicePilot */}
        <section
          id="why-invoicepilot"
          className="scroll-mt-28 border-b border-white/10"
        >
          <div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 lg:px-8 lg:py-24">
            <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]">
              <div>
                <p className="text-sm font-medium uppercase tracking-[0.22em] text-gold">
                  Why InvoicePilot
                </p>

                <h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">
                  AI assists the workflow. Your business stays in control.
                </h2>

                <p className="mt-5 max-w-xl text-lg leading-8 text-white/55">
                  InvoicePilot separates language understanding from business
                  rules, pricing, calculations, and final approval.
                </p>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                {PRINCIPLES.map((principle) => (
                  <div
                    key={principle.title}
                    className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"
                  >
                    <h3 className="font-serif text-2xl">
                      {principle.title}
                    </h3>

                    <p className="mt-3 text-sm leading-6 text-white/50">
                      {principle.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Feedback */}
        <section
          id="feedback"
          className="scroll-mt-28 border-b border-white/10"
        >
          <div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 lg:px-8 lg:py-24">
            <div className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-8 sm:p-12">
              <div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center">
                <div className="max-w-2xl">
                  <p className="text-sm font-medium uppercase tracking-[0.22em] text-gold">
                    Feedback
                  </p>

                  <h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">
                    Help shape InvoicePilot.
                  </h2>

                  <p className="mt-5 text-lg leading-8 text-white/55">
                    Have an idea, found something confusing, or want to suggest
                    an improvement? We would love to hear your feedback.
                  </p>
                </div>

                <a
                  href="mailto:feedback@invoicepilot.demo?subject=InvoicePilot%20Feedback"
                  className="inline-flex rounded-full bg-white px-7 py-3.5 font-medium text-ink transition hover:-translate-y-0.5 hover:bg-white/90"
                >
                  Send feedback
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* Final CTA */}
        <section>
          <div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 lg:px-8 lg:py-24">
            <div className="rounded-[2rem] border border-gold/20 bg-gold p-8 text-ink sm:p-12 lg:p-16">
              <div className="max-w-3xl">
                <p className="text-sm font-medium uppercase tracking-[0.22em] text-ink/55">
                  Ready to get started?
                </p>

                <h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">
                  Create an invoice from your next customer message.
                </h2>

                <p className="mt-5 max-w-2xl text-lg leading-8 text-ink/65">
                  Start with a customer request, verify the services and
                  prices, review the calculated totals, and approve the
                  invoice before exporting it.
                </p>

                <div className="mt-8 flex flex-wrap gap-4">
                  <Link
                    href="/signup"
                    className="rounded-full bg-ink px-7 py-3.5 font-medium text-white transition hover:-translate-y-0.5 hover:bg-ink/90"
                  >
                    Get started
                  </Link>

                  <Link
                    href="/login"
                    className="rounded-full border border-ink/20 px-7 py-3.5 font-medium text-ink transition hover:bg-black/5"
                  >
                    I already have an account
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/10">
        <div className="mx-auto max-w-7xl px-5 py-12 sm:px-6 lg:px-8">
          <div className="grid gap-10 md:grid-cols-[1.5fr_1fr_1fr]">
            {/* Brand */}
            <div>
              <Link href="/" className="inline-flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gold text-ink">
                  <span className="font-serif text-lg font-bold">IP</span>
                </div>

                <span className="font-serif text-xl">
                  InvoicePilot AI
                </span>
              </Link>

              <p className="mt-5 max-w-sm text-sm leading-6 text-white/45">
                AI-assisted invoicing that turns customer messages into
                structured, price-verified invoices with human review before
                export.
              </p>

              <p className="mt-5 text-sm text-white/35">
                Built for the KODNEXUS AI BUILD BATTLE.
              </p>
            </div>

            {/* Product */}
            <div>
              <p className="text-sm font-medium text-white/80">Product</p>

              <div className="mt-4 space-y-3">
                <a
                  href="#features"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  Features
                </a>

                <a
                  href="#how-it-works"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  How it works
                </a>

                <a
                  href="#why-invoicepilot"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  Why InvoicePilot
                </a>

                <Link
                  href="/signup"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  Get started
                </Link>
              </div>
            </div>

            {/* Account */}
            <div>
              <p className="text-sm font-medium text-white/80">Account</p>

              <div className="mt-4 space-y-3">
                <Link
                  href="/login"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  Sign in
                </Link>

                <Link
                  href="/signup"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  Create account
                </Link>

                <a
                  href="#feedback"
                  className="block text-sm text-white/45 transition hover:text-white"
                >
                  Send feedback
                </a>
              </div>
            </div>
          </div>

          <div className="mt-10 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-white/30 sm:flex-row sm:items-center sm:justify-between">
            <p>© 2026 InvoicePilot AI. All rights reserved.</p>

            <p>
              AI interprets. Your catalog prices. The application calculates.
              You approve.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}